openapi: 3.0.0
servers:
  - url: https://restcountries.com/v3.1
info:
  description: country details
  title: country details
  version: 1.0.0
paths:
  /all:
    get:
      description: |
        Fetch current comic and metadata.
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/details"
          description: OK
components:
  schemas:
    details:
      x-flow-type:
          name: countrydetails
      x-flow-query:
          path: /all
          operation: get    
      properties:
        cca2:
          type: string
        cca3:
          type: string
